import LocalizedStrings from 'react-localization'

export const strings = new LocalizedStrings({
  en: {
    add: 'Add',
    amount: 'Amount',
    product: 'Product',
    product_hint: 'Milk, Butter...',
    remove: 'Remove',
    create: 'Create',
    list_create_hint: 'e.g. Grocery list',
    log_out: 'Log Out',
    source_code: 'Source Code',
    log_in_auth0: 'Log In',
    log_in_description: 'Online Shopping List application. Access anywhere!',
    collected: 'Collected',
    clear_collected: 'Clear collected',
    share_title: 'Share link copied!',
    share_body: 'Share link for list "{0}" copied to clipboard',
    remove_title: 'Delete list?',
    remove_body: 'Are you sure you want to delete list "{0}"?',
    close: 'Close',
  },
  fi: {
    add: 'Lisää',
    amount: 'Määrä',
    product: 'Tuote',
    product_hint: 'Maitoa, voita...',
    remove: 'Poista',
    create: 'Luo',
    list_create_hint: 'Esim. Ruokakauppa',
    log_out: 'Kirjaudu ulos',
    source_code: 'Lähdekoodi',
    log_in_auth0: 'Kirjaudu',
    log_in_description: 'Aina saatavilla oleva Kauppalista-sovellus!',
    collected: 'Kerätty',
    clear_collected: 'Tyhjennä kerätyt',
    share_title: 'Jakolinkki kopioitu!',
    share_body: 'Jakolinkki listalle "{0}" kopioitu leikepöydälle',
    remove_title: 'Vahvista poisto',
    remove_body: 'Poistetaanko lista "{0}"?',
    close: 'Sulje',
  },
})